apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-nfs-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: /srv/nfs/cifar10
    server: 192.168.1.156
  persistentVolumeReclaimPolicy: Retain
